apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rtbd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rtbd
    app.kubernetes.io/part-of: byoc-app-yqpp
  name: rtbd
spec:
  rules:
  - host: rtbd-byoc-ddnl-tenant.apps.924a1a59cc24df2204f8.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: rtbd
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
